[package]
name = "neutron-reserve"
version = "0.1.0"
authors = ["Sergey Ratiashvili <sergey.r@p2p.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
neutron-sdk = { package = "neutron-sdk", version = "0.6.1" }
cosmwasm-std = { version = "1.3.0" }
cw-storage-plus = "1.1.0"
schemars = "0.8.8"
exec-control = { path = "../../../packages/exec-control" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cwd-macros = { path = "../../../packages/cwd-macros" }

[dev-dependencies]
cosmwasm-schema = { version = "1.3.0", default-features = false }
