[package]
name = "neutron-vesting-lp-vault"
version = "0.1.0"
authors = ["Sergei Sotnikov <sergei.s@p2p.org>", "Murad Karammaev <karammaev.murad@p2p.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

[dependencies]
serde = { version = "1.0.149", default-features = false, features = ["derive"] }
schemars = "0.8.8"
cwd-macros = { path = "../cwd-macros" }
cosmwasm-std = { version = "1.3.0" }
thiserror = { version = "1.0" }
