[package]
name = "neutron-subdao-timelock-single"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neutron_bindings = { package = "neutron-sdk", version = "0.1.0" }
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }