[package]
name = "neutron-subdao-timelock-single"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neutron-sdk = { package = "neutron-sdk", git = "https://github.com/neutron-org/neutron-sdk.git", rev = "858deb8a3cebb0012f7f27d15a8fe4b353888a9d" }
cosmwasm-std = { version = "1.3.0" }
schemars = "0.8.8"
serde = { version = "1.0.175", default-features = false, features = ["derive"] }
