[package]
name = "neutron-lockdrop-vault"
version = "0.1.0"
authors = ["Sergei Sotnikov <sergei.s@p2p.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cwd-macros = { path = "../cwd-macros" }
cwd-interface = { path = "../cwd-interface" }
schemars = "0.8"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }