[package]
name = "neutron-subdao-core"
version = "0.1.0"
authors = ["Sergei Sotnikov <sergei.s@p2p.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neutron-sdk = { package = "neutron-sdk", git = "https://github.com/neutron-org/neutron-sdk.git", rev = "d5656d0a830b6a6604b2471e7c2e72863d9c60ba" }
cosmwasm-std = { version = "1.3.0" }
schemars = "0.8"
serde = { version = "1.0.149", default-features = false, features = ["derive"] }
cwd-macros = { path = "../cwd-macros" }
cwd-voting = { path = "../cwd-voting" }
cw-utils = { version = "1.0.1" }
cwd-interface = { path = "../cwd-interface" }
cw2 = "0.13"
exec-control = { path = "../exec-control" }
thiserror = { version = "1.0" }
