[package]
name = "cwd-voting"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "Types and methods for CosmWasm DAO voting."

[dependencies]
neutron-sdk = { package = "neutron-sdk", git = "https://github.com/neutron-org/neutron-sdk.git", rev = "d5656d0a830b6a6604b2471e7c2e72863d9c60ba" }
cosmwasm-std = { version = "1.3.0" }
schemars = "0.8"
serde = { version = "1.0.149", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw20 = "0.13"
cwd-interface = { path = "../cwd-interface" }
cwd-macros = { path = "../cwd-macros" }
cwd-core = { path = "../../contracts/dao/cwd-core" }
cw-denom = { path = "../cw-denom" }
cw-utils = "0.13"
cw-storage-plus = "1.1.0"
