[package]
name = "exec-control-macros"
version = "0.1.0"
authors = ["Sergei Sotnikov <sergei.s@p2p.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron/neutron-dao"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
schemars = "0.8"
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
